name: Build images

on:
  schedule:
  - cron: '0 14 * * 1'
  push:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.builds.name }}
    runs-on: ubuntu-latest
    strategy:
      # Dont cancel entire job if one failed
      fail-fast: false
      matrix:
        builds:
          - name: Debian 11
            codename: debian-11
          - name: Debian 12
            codename: debian-12
          - name: Debian 13
            codename: debian-13
          - name: Debian Testing
            codename: debian-testing
          - name: Alma Linux 8
            codename: almalinux-8
          - name: Alma Linux 9
            codename: almalinux-9
          - name: Alma Linux 10
            codename: almalinux-10
          - name: Rocky Linux 8
            codename: rockylinux-8
          - name: Rocky Linux 9
            codename: rockylinux-9
          - name: Rocky Linux 10
            codename: rockylinux-10
          - name: Ubuntu 24.04
            codename: ubuntu-24_04
          - name: Ubuntu 26.04
            codename: ubuntu-26_04
          - name: Arch Linux
            codename: archlinux
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup packer
        uses: hashicorp/setup-packer@v3.4.0
        with:
          version: '1.15.4'

      - uses: extractions/setup-just@v4
        with:
          just-version: '1.56.0'

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install qemu-utils qemu-kvm -y

      - name: Build
        env:
          ALIST_UPLOAD_DOMAIN: ${{ secrets.ALIST_UPLOAD_URL }}
          ALIST_USERNAME: ${{ secrets.ALIST_USERNAME }}
          ALIST_PASSWORD: ${{ secrets.ALIST_PASSWORD }}
        run: |
          just build "${{ matrix.builds.codename }}"
          bash .github/scripts/upload-alist.sh "${{ matrix.builds.codename }}.qcow2" "/Local/VirtualMachineImages"
